### PR TITLE
Fix some statistics view issues

### LINKED ISSUE #160: [BUG] Songs played displays 0 in the stats view
See title

### PR DESCRIPTION
**Pull request by Cesan**
Closes #160

Also adds a timer to update the player age

### CODE REVIEW

File: OsuPlayer/Views/StatisticsViewModel.cs [hunk 1]
```diff
@@ -81,31 +93,35 @@ public StatisticsViewModel()
...
+        this.RaisePropertyChanged(nameof(PlayerAge));
+    }
 
-        // note: MinValue is 1/1/1 so we have to subtract...
-        var years = time.Year - 1;
-        var months = time.Month - 1;
-        var days = time.Day - 1;
+    private void UpdateDateNonApi()
+    {
+        _playerAgeTime += TimeSpan.FromSeconds(1);
```
Comment (Founntain) [inline OsuPlayer/Views/StatisticsViewModel.cs:122]: Maybe instead of simply adding one second, why not just call `UpdateDate()` to refresh it to the actuall value?
Or did you tried that out and it worked wonky?

Comment (Cesan) [reply OsuPlayer/Views/StatisticsViewModel.cs:122]: It worked but I wanted to reduce API calls, calling the API for a date which can be updated like this seems pretty wasted to me.

Comment (Founntain) [reply OsuPlayer/Views/StatisticsViewModel.cs:122]: `UpdateDate()` doesn't call the API at all
```CSharp
private void UpdateDate()
{
    _playerAgeTime = DateTime.Now.Subtract(new DateTime(2017, 11, 1));

    this.RaisePropertyChanged(nameof(PlayerAge));
}
```

Comment (Cesan) [reply OsuPlayer/Views/StatisticsViewModel.cs:122]: Oh wait, i mistook something, this does not call the api even xD

Comment (Founntain) [reply OsuPlayer/Views/StatisticsViewModel.cs:122]: I'll fix that

**Review by Founntain — APPROVED** [review]
After the changes, it looks good to me
